name: Dependency Diff
description: Summarise differences between dependency versions when upgrading.
author: James Garbutt (@43081j)

branding:
  icon: zap
  color: 'gray-dark'

inputs:
  base-ref:
    description: 'Base ref to compare against (defaults to main or PR target)'
    required: false
  github-token:
    description: 'The GitHub token for authentication.'
    required: true
    default: ${{ github.token }}
  pr-number:
    description: 'The number of the pull request to comment on.'
    required: true
    default: ${{ github.event.pull_request.number }}
  dependency-threshold:
    description: 'Threshold for warning about significant increase in number of dependencies'
    required: false
    default: '10'
  size-threshold:
    description: 'Threshold (in bytes) for warning about significant increase in package size'
    required: false
    default: '100000'
  base-packages:
    description: 'Glob pattern for base branch pack files (e.g., "./base-packs/*.tgz")'
    required: false
  source-packages:
    description: 'Glob pattern for source branch pack files (e.g., "./source-packs/*.tgz")'
    required: false
  pack-size-threshold:
    description: 'Threshold (in bytes) for warning about significant increase in total pack size'
    required: false
    default: '50000'
  duplicate-threshold:
    description: 'Threshold for warning about packages with multiple versions'
    required: false
    default: '1'

runs:
  using: node24
  main: main.js
